# Welcome to Jekyll!
#

# Site settings
title: WINNITRON
description: |
  An open source platform for indie
  arcade machines and games.
owner: Winnitron Network # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: hi@winnitron.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://winnitron.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/Winnitron1000
  github: https://github.com/winnitron
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  reddit: https://reddit.com/r/winnitron
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
paginate:     4
permalink:    /news/posts/:title
paginate_path: "/news/page:num/"
date_format: "%b %-d, %Y"

# Google services
#google_analytics:   ''
#google_verification:
